start-at-login = true
after-login-command = []
key-mapping.preset = 'qwerty'

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 6

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

[gaps]
outer.top =        8
outer.bottom =     8
outer.left =       4
outer.right =      4
inner.horizontal = 8
inner.vertical =   8

[mode.main.binding]
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

alt-semicolon = [
  'mode service',
]

alt-tab = 'workspace-back-and-forth'
alt-slash = 'layout tiles accordion'
alt-comma = 'layout horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-d = 'workspace D'
alt-b = 'workspace B'
alt-s = 'workspace S'
alt-x = 'workspace X'

alt-shift-d = 'move-node-to-workspace D'
alt-shift-b = 'move-node-to-workspace B'
alt-shift-s = 'move-node-to-workspace S'
alt-shift-x = 'move-node-to-workspace X'

[workspace-to-monitor-force-assignment]
S = [ 'secondary', 'main' ]

[mode.service.binding]
esc = [
  'reload-config', 
  'mode main', 
]

f = [
  'layout floating tiling', 
] 

minus = 'resize smart -50'
equal = 'resize smart +50'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'net.imput.helium'
check-further-callbacks = true
if.window-title-regex-substring = 'Picture-in-Picture'
run = ['layout floating']